In [ ]:
faqs = """About the Program
What is the course fee for  Data Science Mentorship Program (DSMP 2023)
The course follows a monthly subscription model where you have to make monthly payments of Rs 799/month.
What is the total duration of the course?
The total duration of the course is 7 months. So the total course fee becomes 799*7 = Rs 5600(approx.)
What is the syllabus of the mentorship program?
We will be covering the following modules:
Python Fundamentals
Python libraries for Data Science
Data Analysis
SQL for Data Science
Maths for Machine Learning
ML Algorithms
Practical ML
MLOPs
Case studies
Will Deep Learning and NLP be a part of this program?
No, NLP and Deep Learning both are not a part of this program’s curriculum.
What if I miss a live session? Will I get a recording of the session?
Yes all our sessions are recorded, so even if you miss a session you can go back and watch the recording.
Where can I find the class schedule?
What is the time duration of all the live sessions?
Roughly, all the sessions last 2 hours.
What is the language spoken by the instructor during the sessions?
Hinglish
How will I be informed about the upcoming class?
You will get a mail from our side before every paid session once you become a paid user.
Can I do this course if I am from a non-tech background?
Yes, absolutely.
I am late, can I join the program in the middle?
Absolutely, you can join the program anytime.
If I join/pay in the middle, will I be able to see all the past lectures?
Yes, once you make the payment you will be able to see all the past content in your dashboard.
Where do I have to submit the task?
You don’t have to submit the task. We will provide you with the solutions, you have to self evaluate the task yourself.
Will we do case studies in the program?
Yes.
Where can we contact you?
You can mail us at nitish.campusx@gmail.com
Payment/Registration related questions
Where do we have to make our payments? Your YouTube channel or website?
You have to make all your monthly payments on our website. Here is the link for our website - https://learnwith.campusx.in/
Can we pay the entire amount of Rs 5600 all at once?
Unfortunately no, the program follows a monthly subscription model.
What is the validity of monthly subscription? Suppose if I pay on 15th Jan, then do I have to pay again on 1st Feb or 15th Feb
15th Feb. The validity period is 30 days from the day you make the payment. So essentially you can join anytime you don’t have to wait for a month to end.
What if I don’t like the course after making the payment. What is the refund policy?
You get a 7 days refund period from the day you have made the payment.
I am living outside India and I am not able to make the payment on the website, what should I do?
You have to contact us by sending a mail at nitish.campusx@gmail.com
Post registration queries
Till when can I view the paid videos on the website?
This one is tricky, so read carefully. You can watch the videos till your subscription is valid. Suppose you have purchased subscription on 21st Jan, you will be able to watch all the past paid sessions in the period of 21st Jan to 20th Feb. But after 21st Feb you will have to purchase the subscription again.
But once the course is over and you have paid us Rs 5600(or 7 installments of Rs 799) you will be able to watch the paid sessions till Aug 2024.
Why lifetime validity is not provided?
Because of the low course fee.
Where can I reach out in case of a doubt after the session?
You will have to fill a google form provided in your dashboard and our team will contact you for a 1 on 1 doubt clearance session
If I join the program late, can I still ask past week doubts?
Yes, just select past week doubt in the doubt clearance google form.
I am living outside India and I am not able to make the payment on the website, what should I do?
You have to contact us by sending a mail at nitish.campusx@gmai.com
Certificate and Placement Assistance related queries
What is the criteria to get the certificate?
There are 2 criterias:
You have to pay the entire fee of Rs 5600
You have to attempt all the course assessments.
I am joining late. How can I pay payment of the earlier months?
You will get a link to pay fee of earlier months in your dashboard once you pay for the current month.
I have read that Placement assistance is a part of this program. What comes under Placement assistance?
This is to clarify that Placement assistance does not mean Placement guarantee. So we dont guarantee you any jobs or for that matter even interview calls. So if you are planning to join this course just for placements, I am afraid you will be disappointed. Here is what comes under placement assistance
Portfolio Building sessions
Soft skill sessions
Sessions with industry mentors
Discussion on Job hunting strategies
"""

In [ ]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

In [ ]:
tokenizer = Tokenizer()

In [ ]:
tokenizer.fit_on_texts([faqs])

In [ ]:
tokenizer.word_index

{'the': 1,
 'you': 2,
 'i': 3,
 'to': 4,
 'a': 5,
 'is': 6,
 'have': 7,
 'of': 8,
 'will': 9,
 'what': 10,
 'can': 11,
 'course': 12,
 'program': 13,
 'for': 14,
 'in': 15,
 'all': 16,
 'sessions': 17,
 'on': 18,
 'be': 19,
 'and': 20,
 'if': 21,
 'am': 22,
 'pay': 23,
 'payment': 24,
 'make': 25,
 'we': 26,
 'this': 27,
 'do': 28,
 'subscription': 29,
 'where': 30,
 'rs': 31,
 'so': 32,
 'session': 33,
 'our': 34,
 'paid': 35,
 'join': 36,
 'able': 37,
 'your': 38,
 'website': 39,
 'placement': 40,
 'fee': 41,
 'monthly': 42,
 'not': 43,
 'get': 44,
 'yes': 45,
 'once': 46,
 'past': 47,
 'feb': 48,
 'assistance': 49,
 'data': 50,
 '7': 51,
 '5600': 52,
 'are': 53,
 'watch': 54,
 'mail': 55,
 'from': 56,
 'contact': 57,
 'us': 58,
 'at': 59,
 'campusx': 60,
 'or': 61,
 'doubt': 62,
 'science': 63,
 'payments': 64,
 '799': 65,
 'month': 66,
 'total': 67,
 'duration': 68,
 'months': 69,
 'learning': 70,
 'case': 71,
 'part': 72,
 'by': 73,
 'late': 74,
 'dashboard': 75,
 'task': 76,
 'do

In [ ]:
len(tokenizer.word_index)

267

In [ ]:
input_sequences = []
for sentence in faqs.split('\n'):
  tokenized_sentence = tokenizer.texts_to_sequences([sentence])[0]
  print(f"{sentence}",tokenized_sentence,f"{len(tokenized_sentence)}")
  for i in range(1,len(tokenized_sentence)):
    print(f"{i}",tokenized_sentence[:i+1])
    input_sequences.append(tokenized_sentence[:i+1])

About the Program [88, 1, 13] 3
1 [88, 1]
2 [88, 1, 13]
What is the course fee for  Data Science Mentorship Program (DSMP 2023) [10, 6, 1, 12, 41, 14, 50, 63, 89, 13, 143, 144] 12
1 [10, 6]
2 [10, 6, 1]
3 [10, 6, 1, 12]
4 [10, 6, 1, 12, 41]
5 [10, 6, 1, 12, 41, 14]
6 [10, 6, 1, 12, 41, 14, 50]
7 [10, 6, 1, 12, 41, 14, 50, 63]
8 [10, 6, 1, 12, 41, 14, 50, 63, 89]
9 [10, 6, 1, 12, 41, 14, 50, 63, 89, 13]
10 [10, 6, 1, 12, 41, 14, 50, 63, 89, 13, 143]
11 [10, 6, 1, 12, 41, 14, 50, 63, 89, 13, 143, 144]
The course follows a monthly subscription model where you have to make monthly payments of Rs 799/month. [1, 12, 90, 5, 42, 29, 91, 30, 2, 7, 4, 25, 42, 64, 8, 31, 65, 66] 18
1 [1, 12]
2 [1, 12, 90]
3 [1, 12, 90, 5]
4 [1, 12, 90, 5, 42]
5 [1, 12, 90, 5, 42, 29]
6 [1, 12, 90, 5, 42, 29, 91]
7 [1, 12, 90, 5, 42, 29, 91, 30]
8 [1, 12, 90, 5, 42, 29, 91, 30, 2]
9 [1, 12, 90, 5, 42, 29, 91, 30, 2, 7]
10 [1, 12, 90, 5, 42, 29, 91, 30, 2, 7, 4]
11 [1, 12, 90, 5, 42, 29, 91, 30, 2, 7, 4, 25]
12 [1,

In [ ]:
input_sequences

[[88, 1],
 [88, 1, 13],
 [10, 6],
 [10, 6, 1],
 [10, 6, 1, 12],
 [10, 6, 1, 12, 41],
 [10, 6, 1, 12, 41, 14],
 [10, 6, 1, 12, 41, 14, 50],
 [10, 6, 1, 12, 41, 14, 50, 63],
 [10, 6, 1, 12, 41, 14, 50, 63, 89],
 [10, 6, 1, 12, 41, 14, 50, 63, 89, 13],
 [10, 6, 1, 12, 41, 14, 50, 63, 89, 13, 143],
 [10, 6, 1, 12, 41, 14, 50, 63, 89, 13, 143, 144],
 [1, 12],
 [1, 12, 90],
 [1, 12, 90, 5],
 [1, 12, 90, 5, 42],
 [1, 12, 90, 5, 42, 29],
 [1, 12, 90, 5, 42, 29, 91],
 [1, 12, 90, 5, 42, 29, 91, 30],
 [1, 12, 90, 5, 42, 29, 91, 30, 2],
 [1, 12, 90, 5, 42, 29, 91, 30, 2, 7],
 [1, 12, 90, 5, 42, 29, 91, 30, 2, 7, 4],
 [1, 12, 90, 5, 42, 29, 91, 30, 2, 7, 4, 25],
 [1, 12, 90, 5, 42, 29, 91, 30, 2, 7, 4, 25, 42],
 [1, 12, 90, 5, 42, 29, 91, 30, 2, 7, 4, 25, 42, 64],
 [1, 12, 90, 5, 42, 29, 91, 30, 2, 7, 4, 25, 42, 64, 8],
 [1, 12, 90, 5, 42, 29, 91, 30, 2, 7, 4, 25, 42, 64, 8, 31],
 [1, 12, 90, 5, 42, 29, 91, 30, 2, 7, 4, 25, 42, 64, 8, 31, 65],
 [1, 12, 90, 5, 42, 29, 91, 30, 2, 7, 4, 25, 42, 64, 8

In [ ]:
max_len = max([len(x) for x in input_sequences])
max_len

57

In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
padded_input_sequences = pad_sequences(input_sequences, maxlen = max_len, padding='pre')

In [ ]:
padded_input_sequences

array([[  0,   0,   0, ...,   0,  88,   1],
       [  0,   0,   0, ...,  88,   1,  13],
       [  0,   0,   0, ...,   0,  10,   6],
       ...,
       [  0,   0,   0, ..., 264,  18, 265],
       [  0,   0,   0, ...,  18, 265, 266],
       [  0,   0,   0, ..., 265, 266, 267]], dtype=int32)

In [ ]:
X = padded_input_sequences[:,:-1]
X[0]

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0, 88], dtype=int32)

In [ ]:
X[1]

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0, 88,  1], dtype=int32)

In [ ]:
X[2]

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0, 10], dtype=int32)

In [ ]:
y = padded_input_sequences[:,-1]

In [ ]:
X.shape

(822, 56)

In [ ]:
y.shape

(822,)

In [ ]:
y[0]

np.int32(1)

In [ ]:
from tensorflow.keras.utils import to_categorical
y = to_categorical(y,num_classes=268)

In [ ]:
y[0]

array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [ ]:
y.shape

(822, 268)

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

In [ ]:
model = Sequential()
model.add(Embedding(268, 100, input_length=56))
model.add(LSTM(150, return_sequences=True))
model.add(LSTM(150))
model.add(Dense(268, activation='softmax'))

In [ ]:
model.compile(loss='categorical_crossentropy', optimizer='adam',metrics=['accuracy'])

In [ ]:
model.fit(X,y,epochs=100)

Epoch 1/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 10s 201ms/step - accuracy: 0.0368 - loss: 5.4646
Epoch 2/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 10s 195ms/step - accuracy: 0.0764 - loss: 4.9919
Epoch 3/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 6s 243ms/step - accuracy: 0.0703 - loss: 4.9910
Epoch 4/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 9s 196ms/step - accuracy: 0.0793 - loss: 4.9294
Epoch 5/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 10s 206ms/step - accuracy: 0.0846 - loss: 4.9001
Epoch 6/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 10s 199ms/step - accuracy: 0.0777 - loss: 4.9763
Epoch 7/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 11s 221ms/step - accuracy: 0.0770 - loss: 4.8791
Epoch 8/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 5s 207ms/step - accuracy: 0.0973 - loss: 4.7442
Epoch 9/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 7s 246ms/step - accuracy: 0.0912 - loss: 4.7085
Epoch 10/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 5s 200ms/step - accuracy: 0.0842 - loss: 4.5999
Epoch 11/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 10s 199ms/step - accuracy: 0.0921 - loss: 4.4370
Epoch 12/100
26/26 ━━━━━━━━━━━━━━━━

In [ ]:
import time
import numpy as np # Import numpy

text = "what is the fee"

for i in range(10):
  # tokenize
  token_text = tokenizer.texts_to_sequences([text])[0]
  # padding
  padded_token_text = pad_sequences([token_text], maxlen=56, padding='pre')
  # predict
  pos = np.argmax(model.predict(padded_token_text)) # Now np is defined

  for word,index in tokenizer.word_index.items():
    if index == pos:
      text = text + " " + word
      print(text)
      time.sleep(2)

In [ ]:
# tokenizer.word_index